# Generated by Django 2.1.4 on 2018-12-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miexamen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listado',
            name='producto',
        ),
        migrations.AddField(
            model_name='listado',
            name='producto',
            field=models.ManyToManyField(to='miexamen.Producto'),
        ),
    ]
